#!/usr/bin/env php
<?php
/**
 * This file is part of the evolver diagnostics project.
 *
 * @copyright Copyright (c) 2015, evolver media GmbH & Co. KG <info@evolver.de>
 * @author Daniel Schröder <daniel.schroeder@gravitymedia.de>
 */

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

foreach (array(__DIR__ . '/../..', __DIR__ . '/..', __DIR__) as $dir) {
    if (file_exists($dir . '/vendor/autoload.php')) {
        require $dir . '/vendor/autoload.php';
        break;
    }
}

unset($dir);

$application = new \Evolver\Diagnostics\Console\Application();
$application->run();
