#!/usr/bin/env php
<?php
/**
 * This file is part of the evolver diagnostics project.
 *
 * @copyright Copyright (c) 2015, evolver media GmbH & Co. KG <info@evolver.de>
 * @author Daniel Schröder <daniel.schroeder@gravitymedia.de>
 */

foreach (array(__DIR__ . '/../..', __DIR__ . '/..', __DIR__) as $dir) {
    if (file_exists($dir . '/vendor/autoload.php')) {
        chdir($dir);
        break;
    }
}

unset($dir);

require 'vendor/autoload.php';

$application = new \Evolver\Diagnostics\Console\Application();
$application->run();
